% %Food Deprivation
% autoHeatMaps("C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Food Deprivation Analysis\Reaction Time Sigmoid Data",...
% "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Food Deprivation Analysis\Reward Choice Sigmoid Data",...
% "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Food Deprivation Analysis\Rotation Points Sigmoid Data",...
% "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Food Deprivation Analysis\Stopping Points Sigmoid Data",...
% "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Food Deprivation Analysis\Travel Pixel Sigmoid Data",...
% "C:\Users\ldd77\OneDrive\Desktop\Raw Figures\Heat Maps\Food Deprivation")
% 
% %Ghrelin
% autoHeatMaps("C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Ghrelin Analysis\Reaction Time Sigmoid Data",...
% "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Ghrelin Analysis\Reward Choice Sigmoid Data",...
% "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Ghrelin Analysis\Rotation Points Sigmoid Data",...
% "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Ghrelin Analysis\Stopping Points Sigmoid Data",...
% "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Ghrelin Analysis\Travel Pixel Sigmoid Data",...
% "C:\Users\ldd77\OneDrive\Desktop\Raw Figures\Heat Maps\Ghrelin")

%Isoflurene
% travelPixelSigmoidTableIsoflurene = getTable("C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Isoflurene Analysis\Travel Pixel Sigmoid Data");
% stoppingPointsSigmoidTableIsoflurene = getTable("C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Isoflurene Analysis\Stopping Points Sigmoid Data");
% rotationPointsSigmoidTableIsoflurene = getTable("C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Isoflurene Analysis\Rotation Points Sigmoid Data");
% reactionTimeSigmoidTableIsoflurene = getTable("C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Isoflurene Analysis\Reaction Time Sigmoid Data");
% rewardChoiceSigmoidTableIsoflurene =getTable("C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Isoflurene Analysis\Reward Choice Sigmoid Data");

%Original Data
% rewardChoiceSigmoidTable = getTable("C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Reward Choice\All Sigmoids");
% reactionTimeSigmoidTable = getTable("C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Reaction Time 1st\All Sigmoids");
% rotationPointsSigmoidTable = getTable("C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Rotation Points\All Sigmoids");
% stoppingPointsSigmoidTable = getTable("C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Stopping Points\All Sigmoids");
% travelPixelSigmoidTable=getTable("C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Travel Pixel\All Sigmoids");

%saline
% autoHeatMaps("C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Saline Analysis\Reaction Time Sigmoid Data",...
% "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Saline Analysis\Reward Choice Sigmoid Data",...
% "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Saline Analysis\Rotation Points Sigmoid Data",...
% "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Saline Analysis\Stopping Points Sigmoid Data",...
% "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Saline Analysis\Travel Pixel Sigmoid Data",...
% "C:\Users\ldd77\OneDrive\Desktop\Raw Figures\Heat Maps\Saline")

%alcohol
% autoHeatMaps("a", ...
%     "a", ...
%     "a", ...
%     "a", ...
%     "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Alcohol Analysis\Reward Choice Sigmoid Data", ...
%     "C:\Users\ldd77\OneDrive\Desktop\Raw Figures\Heat Maps\Alcohol")

%oxy
% autoHeatMaps("C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Oxycodone Analysis\Travel Pixel Sigmoid Data", ...
%     "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Oxycodone Analysis\Stopping Points Sigmoid Data", ...
%     "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Oxycodone Analysis\Rotation Points Sigmoid Data", ...
%     "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Oxycodone Analysis\Reaction Time Sigmoid Data", ...
%     "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\Oxycodone Analysis\Reward Choice Sigmoid Data", ...
%     "C:\Users\ldd77\OneDrive\Desktop\Raw Figures\Heat Maps\Oxy")

autoHeatMaps("C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\New Base Data\Travel Pixel Sigmoid Data", ...
    "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\New Base Data\Stopping Points Sigmoid Data", ...
    "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\New Base Data\Rotation Points Sigmoid Data", ...
    "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\New Base Data\Reaction Time Sigmoid Data", ...
    "C:\Users\ldd77\OneDrive\Desktop\UTEP-Brain-Computation-Lab\Data Analysis\New Base Data\Reward Choice Sigmoid Data", ...
    "C:\Users\ldd77\OneDrive\Desktop\Raw Figures\Heat Maps\New Base Data")